
export const LANGUAGES = {
	'english': 'English',
	'urdu': 'Urdu',
	'hindi': 'Hindi',
	'punjabi': 'Punjabi',
	'arabic': 'Arabic',
	'french': 'French',
	'spanish': 'Spanish',
	'german': 'German',
	'italian': 'Italian',
	'portuguese': 'Portuguese',
	'japanese': 'Japanese',
	'korean': 'Korean',
	'chinese': 'Chinese',
	'farsi': 'Farsi',
	'pashto': 'Pashto',
	'balochi': 'Balochi',
	'sindhi': 'Sindhi',
	'kashmiri': 'Kashmiri',
	'gujrati': 'Gujrati',
	'rajasthani': 'Rajasthani',
	'assamese': 'Assamese',
	'oriya': 'Oriya',
	'marathi': 'Marathi',
	'kannada': 'Kannada',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'malayalam': 'Malayalam',
	'bengali': 'Bengal',
} as const;
